server:
  port: 8080
logging:
  level:
    com.exam: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://1.117.99.103:3306/campus
    username: Campus
    password: rTwd5HPyGAz7cAxH
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j

  servlet:
  #文件上传限制
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.nepenthe.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: MYSQL
