#根据不同的环境(开发环境和生产环境)选额不同的配置文件。开发环境，active的值为dev；生产环境，active的值为prd
#并且要保证在resource目录下创建了application-dev.yml和application-prd.yml两个环境的配置文件。
#项目上线时只需改一下active的值即可使用生产环境配置文件
spring:
  profiles:
    active: prd
